### ISSUE TITLE
Syncronous API

### ISSUE THREAD

**Issue by damienleroux** [APIDevTools/json-schema-ref-parser#14] opened 2016-03-22 10:42 UTC
Hey!

You did a great job here!

I need to use your API syncronously ( because I need it in a syncronous framework). Is there any plan to do it in the future?

Thank you

**Comment by BigstickCarpet** [comment] 2016-03-22 15:19
yeah, that's doable.  obviously, it'll only work in Node though.  Resolving external `$refs` in the browser has to be async, since it has to download the files

**Comment by damienleroux** [comment] 2016-03-22 15:39
Indeed, I need it server side only in my case

**Comment by willfarrell** [comment] 2016-04-02 01:35
+1
Right now I'm using something like:
```javascript
var data, done = false; 
	$RefParser.dereference(schema, function(err, schema) {
		if (err) {
			console.error(err);
                     return done = false;
		}
		  
		...
		done = true;
	});
	require('deasync').loopWhile(function(){return !done;});
	return data;
```

**Comment by noah-sis** [comment] 2016-06-22 19:33
I'd love to see this as well.

**Comment by coltonlw** [comment] 2016-08-23 18:41
+1

**Comment by aaronshaf** [comment] 2016-09-29 16:49
This would make using supertest easier as well. +1

**Comment by Lange** [comment] 2017-06-25 18:37
Apologies for the +1 spam, but I'd love to see this as well. For my use case, I only need synchronous support for resolving local file references. I would not need to synchronously resolve remote HTTP references.

**Comment by BigstickCarpet** [comment] 2017-06-27 15:05
Good news.  I've already started working on a synchronous API  👍

**Comment by Lange** [comment] 2017-07-18 19:41
@BigstickCarpet I have a need for the synchronous API as soon as possible, and would be happy to contribute to help get it ready for release. Is there a branch and list of remaining tasks that I could dive into? Thanks!

**Comment by BigstickCarpet** [comment] 2017-07-20 12:13
Hi @Lange - You can see my work-in-progress [here](https://github.com/BigstickCarpet/json-schema-lib), but it's not finished yet or ready to use.  I'm not quite ready to accept pull-requests yet, because the code is still very much in flux.  This is a complete rewrite with a brand-new API, and nothing is fully solidified yet.  It already has a [synchronous API](https://github.com/BigstickCarpet/json-schema-lib/blob/9c57af8fcfce1067fd5a7be1a1cd42cdf31f8e91/lib/api/JsonSchemaLib/JsonSchemaLib.js#L61-L108) though, and [a few tests](https://github.com/BigstickCarpet/json-schema-lib/blob/9c57af8fcfce1067fd5a7be1a1cd42cdf31f8e91/test/specs/Schema/toJSON.spec.js#L53-L73) that use it, so I'm definitely making good progress.  I hope to have an alpha version ready for public feedback and testing within a few weeks.

**Comment by Lange** [comment] 2017-07-20 15:25
Understood - thanks for the reply @BigstickCarpet!

**Comment by mashpie** [comment] 2017-12-12 18:16
add +1 to get notified - thanks a lot :)

**Comment by willfarrell** [comment] 2017-12-12 18:37
@mashpie For future reference there is a `Subscribe` button on the right side under notifications.

**Comment by mashpie** [comment] 2017-12-13 09:22
@willfarrell true, wanted to opt my plus one in addition

**Comment by MikeTaylor** [comment] 2018-05-23 19:28
Did anything ever come of this? I, too, would very very much love to do
```
const expandedSchema = $RefParser.dereferenceNowDammit(mySchema);
```
without having to mess about with callbacks and promises.

**Comment by MikeTaylor** [comment] 2018-05-24 03:19
In the mean time, I made this: https://github.com/MikeTaylor/json-schema-ref-parser-sync

I'm not proud of it, but it works. I hope it's of use to someone else.

**Comment by epicfaace** [comment] 2019-01-21 00:44
This would be great to implement.

**Comment by joelgallant** [comment] 2019-02-21 05:22
I've had to manually write this logic in my application because it supports a sync & async API. Does anyone have a rough outline of which APIs this would need to support? A bit of direction and I'd be willing to work on it.

**Comment by mhuggins** [comment] 2020-02-27 16:55
The deasync solution mentioned by @willfarrell and used by apidoc-plugin-schema unfortunately no longer works with the latest versions of json-schema-ref-parser since it's built on async/await.

**Comment by mhuggins** [comment] 2020-02-27 17:14
I think this can be fixed by calling `process.nextTick()` (for node, anyway) within the deasync loop, but I haven't reached a final solution yet.

**Comment by llirikkk** [comment] 2020-04-17 08:24
This library works for me: https://www.npmjs.com/package/json-schema-deref-sync

**Comment by philsturgeon** [comment] 2020-04-17 09:04
Is this still necessary in an async/await world? It seems like the complaints of “I don’t want to mess around with callbacks and promises” would no longer be relevant with a bit of await now?

**Comment by Lange** [comment] 2020-04-17 14:52
@philsturgeon The exception is in `constructors`, which must be sync.

**Comment by llirikkk** [comment] 2020-04-18 14:21
@philsturgeon the problem is not in the complexity, but in that some use cases require synchronous behaviour. With async version the users of my function had to always add await, when invoking the function. But the often forgot to do this, because the function was meant to be used in a synchronous context. And because of this they often ended up with unhandled promise rejection errors, which were swallowed by Node.

**Comment by JamesMessinger** [comment] 2020-04-18 17:57
The problem is that the library currently does too much in a single function.  Functions like `dereference()` and `bundle()` currently do all of the following:

1. Read files from disk
2. Download files from URLs
3. Parse data from YAML, JSON, etc.
4. Resolve all the `$ref` pointers in each file
5. Dereference all `$ref` pointers in each file

Only #1 and #2 need to be async.  All the rest can be done synchronously.  And, indeed, many people don't need #1 and #2 at all because they already have the schema object in memory, not in a file on disk.

I'm currently working on separating the above functionality into separate functions so they'll work better with workflows that _could_ be fully synchronous.

**Comment by iPherian** [comment] 2020-09-12 13:57
@philsturgeon Node is still heavily synchronous. I have a node module which does dereference() while creating module.exports and it's used by most of the program.

**Comment by philsturgeon** [comment] 2020-09-14 11:32
I'm considering my question answered already folks, don't need to keep explaining it! 😅 

From @JamesMessinger 

> I'm currently working on separating the above functionality into separate functions so they'll work better with workflows that could be fully synchronous.

Looking forward to that.

**Comment by michaelmelody91** [comment] 2020-09-24 13:25
Hey all, reaching out in desperation as a bit of a JS/Node noob when it comes to async/await... I've a couple of questions that if anyone could help me with or at least point me in the right direction, I'd be massively grateful.

My use case is that I'm attempting to return an object from a function and within that function I'm required to parse out a schema.

1. Other that using https://github.com/APIDevTools/json-schema-ref-parser/issues/14#issuecomment-204624236 (which I've not been able to use, a previous comment mentions that this is no longer possible with the latest version of the parser), is there any way to hack a sycnronous implementation of this - I've attempted to use a callback to set a `done` variable to true in combination with a `while(!done)` - again, I've not been able to configure this correctly and I fall into a never ending loop. _See below._

```
    $RefParser.dereference(doc, (error, result) => {
      console.log('trying to deref....')
      savedError = error;
      savedResult = result;
      done = true;
    });

    while(!done){}
```

2. What prevents the `deasync` module working with the latest version of the parser?

**Comment by anttiviljami** [comment] 2020-09-24 19:03
@michaelmelody91 and for anyone interested, I was able to get synchronous dereferencing for a schema object like so:

```javascript
import $RefParser from '@apidevtools/json-schema-ref-parser';
import _dereference from '@apidevtools/json-schema-ref-parser/lib/dereference';

export const dereference = (schema) => {
  const parser = new $RefParser();
  parser.parse(schema);
  parser.schema = schema;
  _dereference(parser); // NOTE: mutates schema
  return schema;
};
```

**Comment by anttiviljami** [comment] 2020-09-24 19:06
The caveat of the solution above is that it mutates the original object, which may not be what you want.

You should probably make a deep copy of the schema object before running `require('@apidevtools/json-schema-ref-parser/lib/dereference')` on it.

**Comment by philsturgeon** [comment] 2021-05-21 09:08
Ok there are a couple of workarounds suggested and the new library will have a synchronous option, so lets call this thread a day. Thank you!

**Closed by philsturgeon** 2021-05-21 09:08 UTC
Labels: enhancement

**Comment by minhpfg** [comment] 2021-06-16 20:28
> Ok there are a couple of workarounds suggested and the new library will have a synchronous option, so lets call this thread a day. Thank you!

Hi @philsturgeon, can you elaborate more on "the new library will have a synchronous option"? What is this "new library" you speak of?

**Comment by philsturgeon** [comment] 2021-06-17 10:57
Over here: https://github.com/APIDevTools/json-schema-reader

This tool will eventually replace json-schema-ref-parser but is not yet complete. The goal is to continue meaningful changes over there whilst getting it ship shape, although priorities and availability for the maintainers is a struggle at the moment. 

If you'd like to muck about with that lib and see how far you get that'd be handy.
