### ISSUE TITLE
Internal $id reference not derefernced

### ISSUE THREAD

**Issue by zuker** [APIDevTools/json-schema-ref-parser#136] opened 2019-09-10 12:49 UTC
STR:
1. Create file `schema.json`
```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",

  "definitions": {
    "address": {
      "$id": "#address",
      "type": "object",
      "properties": {
        "street_address": { "type": "string" },
        "city":           { "type": "string" },
        "state":          { "type": "string" }
      },
      "required": ["street_address", "city", "state"]
    }
  },

  "type": "object",

  "properties": {
    "billing_address": { "$ref": "#address" },
    "shipping_address": { "$ref": "#address" }
  }
}
```
this actually example from https://json-schema.org/understanding-json-schema/structuring.html#using-id-with-ref

2. `npm i json-schema-ref-parser`
3. `node -e "(async () => { console.log(JSON.stringify(await require('json-schema-ref-parser').dereference(require('./schema.json')), null, 2))})()"`

Actual result:
```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "address": {
      "$id": "#address",
      "type": "object",
      "properties": {
        "street_address": {
          "type": "string"
        },
        "city": {
          "type": "string"
        },
        "state": {
          "type": "string"
        }
      },
      "required": [
        "street_address",
        "city",
        "state"
      ]
    }
  },
  "type": "object",
  "properties": {
    "billing_address": {
      "$ref": "#address"
    },
    "shipping_address": {
      "$ref": "#address"
    }
  }
}
```

Expected result:
`properties.billing_address` and `properties.shipping_address` are dereferenced

**Comment by zuker** [comment] 2019-09-10 12:52
Seems this test https://github.com/APIDevTools/json-schema-ref-parser/blob/v7.1.1/test/specs/internal/bundled.js#L7
actualy not testing the case since `#fragment` has no other props

**Comment by philsturgeon** [comment] 2022-11-26 13:27
Duplicate of #145.

**Closed by philsturgeon** 2022-11-26 13:27 UTC
