### ISSUE TITLE
Resolve function converts path to lowercase

### ISSUE THREAD

**Issue by neosat55** [APIDevTools/json-schema-ref-parser#239] opened 2021-07-06 13:01 UTC
https://github.com/APIDevTools/json-schema-ref-parser/blob/main/lib/util/url.js#L26

This function needs to be replaced because it is considered [legacy](https://nodejs.org/api/url.html#url_url_resolve_from_to) and  leads to unexpected behavior by converting path to lowercase. [Example case](https://replit.com/@neosat55/AnnualOvercookedSandbox#index.js)

expected behavior:
foo://barTest -> foo://barTest
actual: 
foo://barTest -> foo://bartest

**Comment by afranke** [comment] 2022-02-02 09:46
Duplicate of #49 ?

**Comment by neosat55** [comment] 2022-02-02 13:53
@afranke yea, i think so

**Closed** 2024-03-06 04:59 UTC
