### ISSUE TITLE
Circular reference causes "Maximum call stack size exceeded"

### ISSUE THREAD

**Issue by rbren** [APIDevTools/json-schema-ref-parser#40] opened 2017-05-02 16:10 UTC
Here's my schema (simplified from the [Gmail API's Message object](https://github.com/APIs-guru/openapi-directory/blob/master/APIs/googleapis.com/gmail/v1/swagger.yaml))

```json
{
  "definitions": {
    "MessagePart": {
      "type": "object",
      "properties": {
        "parts": {
          "type": "array",
          "items": {"$ref": "#/definitions/MessagePart"}
        }
      }
    }
  },
  "title": "Message",
  "type": "object",
  "properties": {
    "part": {"$ref": "#/definitions/MessagePart"}
  }
}
```

```
> let rp = require('json-schema-ref-parser')
> rp.dereference(sch).then(r => console.log(r))
Promise { <pending> }
> (node:11443) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): RangeError: Maximum call stack size exceeded
```

**Comment by bobby-brennan** [comment] 2017-05-02 16:11
Also worth noting - I don't think this is a duplicate of #36, as `resolve()` seems to work fine with this schema.

**Comment by philsturgeon** [comment] 2021-05-21 09:04
Running this script in 9.0.7 I get:

```
{
  definitions: { MessagePart: { type: 'object', properties: [Object] } },
  title: 'Message',
  type: 'object',
  properties: { part: { type: 'object', properties: [Object] } }
}
```

🥳

**Closed by philsturgeon** 2021-05-21 09:04 UTC
