### ISSUE TITLE
Ref parser is not resolving direct references.

### ISSUE THREAD

**Issue by tofuseblue** [APIDevTools/json-schema-ref-parser#41] opened 2017-06-20 14:55 UTC
Following schema will not be resolved.
```
{
  "$schema": "http://json-schema.org/schema#",
  "$id": "test-schema",
  "definitions": {
    "i_ref_obj": {
      "type": "object",
      "properties": {
        "file": {
          "type": "string"
        }
      },
      "required": [
        "file"
      ]
    }
  },
  "$ref": "#/definitions/i_ref_obj"
}
```

**Comment by BigstickCarpet** [comment] 2017-06-21 11:57
This isn't technically a valid schema, since a JSON Reference is _only_ supposed to contain a `$ref` property and it doesn't make sense for a reference to point to another property of itself.  I suggest that you rewrite your schema to be valid.

That said, json-schema-ref-parser definitely _should_ have thrown an error or something rather than just failing silently, so I've marked this issue as a bug for that reason.

**Comment by tofuseblue** [comment] 2017-06-21 12:29
Well as I interpret it the json-schema.org draft-04 and 06 both specifies $ref as valid attribute on a schema . And as far as "doesn't" make sense. To me it makes much sense as a shorter syntax of using anyOf with just one reference.
```
allOf: [ "$ref": "#/definitions/i_ref_obj" ]
```
Note: that my original example is condensed. The real world usage is to reference another schema in combination with "parameters" where the reference effectively becomes an "extends"

**Comment by BigstickCarpet** [comment] 2017-06-21 13:02
Quoting the [JSON Schema specification](http://json-schema.org/latest/json-schema-core.html#rfc.section.8):

> All other properties in a "$ref" object MUST be ignored.

Quoting the [JSON Reference specification](https://tools.ietf.org/html/draft-pbryan-zyp-json-ref-03#section-3):

> Any members other than "$ref" in a JSON Reference object SHALL be
   ignored.

The intention of a JSON Reference is that it should _only_ have a `$ref` property.  It doesn't make sense to embed a JSON Schema within a JSON Reference, and attempting to resolve or dereference such a reference leads to undefined behavior.

**Comment by tofuseblue** [comment] 2017-06-21 13:20
ok, so what you are arguing here is that the json-shema specification should really accept { "$ref": "..." } rather than just "$ref": "" because in the later the schema object itself becomes a $ref object, hence all schema properties should be ignored.

**Comment by BigstickCarpet** [comment] 2017-06-21 13:24
Correct.  Essentially your current schema is really just one top-level JSON Reference with a JSON Schema _embedded_ inside it, which isn't valid.  In this case, it would make sense to just eliminate the JSON Reference and the `definitions` list entirely and just write the schema like this:

```json
{
  "$schema": "http://json-schema.org/schema#",
  "$id": "test-schema",
  "title": "i_ref_obj",
  "type": "object",
  "properties": {
    "file": {
      "type": "string"
    }
  },
  "required": [
    "file"
  ]
}
```

**Comment by Relequestual** [comment] 2019-05-01 15:05
I can confirm this is correct. Think you can probably close this one =]

**Closed** 2019-05-01 23:15 UTC
Labels: bug
